version: "3.8"
services:
  app:
    container_name: nestjs-cqrs
    image: nestjs-cqrs:1.0.0
    build:
      context: .
      target: ${NODE_ENV}
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
    tty: true
    command: yarn start:${NODE_ENV}
    ports:
      - ${PORT}:${PORT}
    networks:
      - nestjs-network
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: unless-stopped
  db:
    container_name: nestjs-cqrs-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

networks:
  nestjs-network:

volumes:
  docker-nest-postgres: